"use client"

import * as React from "react"
import QRCode from "qrcode"
import jsPDF from "jspdf"
import { Calendar, MapPin, Download, CheckCircle, Clock } from "lucide-react"

interface TicketData {
  id: string
  ticket_code: string
  registration: {
    id: string
    created_at: string
    events: {
      id: string
      title: string
      description: string
      venue: string
      event_date: string
      event_time: string
      categories?: { name: string; type: string }
    }
  }
}

interface TicketsClientProps {
  initialTickets: TicketData[]
}

export function TicketsClient({ initialTickets }: TicketsClientProps) {
  const [tickets, setTickets] = React.useState<TicketData[]>(initialTickets)
  const [qrUrls, setQrUrls] = React.useState<{ [key: string]: string }>({})

  // Generate QR code data URLs on mount
  React.useEffect(() => {
    tickets.forEach(async (t) => {
      try {
        const url = await QRCode.toDataURL(t.ticket_code, {
          margin: 1,
          width: 256,
          color: {
            dark: "#000000",
            light: "#ffffff",
          },
        })
        setQrUrls((prev) => ({ ...prev, [t.ticket_code]: url }))
      } catch (err) {
        console.error("Error generating QR:", err)
      }
    })
  }, [tickets])

  const downloadPDF = (t: TicketData, qrUrl: string) => {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a5", // Elegant A5 card format
    })

    const event = t.registration.events

    // Background color styling
    doc.setFillColor(15, 15, 17) // Dark color background
    doc.rect(0, 0, 148, 210, "F")

    // Draw card borders/gradients mockup
    doc.setDrawColor(36, 36, 40)
    doc.setLineWidth(1)
    doc.line(10, 10, 138, 10)
    doc.line(10, 10, 10, 200)
    doc.line(138, 10, 138, 200)
    doc.line(10, 200, 138, 200)

    // Header styling
    doc.setFillColor(33, 150, 243) // Primary blue bar
    doc.rect(10, 10, 128, 15, "F")

    doc.setFont("Helvetica", "bold")
    doc.setFontSize(14)
    doc.setTextColor(255, 255, 255)
    doc.text("CREW ARENA ENTRY TICKET", 24, 20)

    // Ticket Code
    doc.setFontSize(9)
    doc.setFont("Helvetica", "normal")
    doc.setTextColor(150, 150, 150)
    doc.text(`TICKET NO: ${t.ticket_code}`, 15, 40)

    // Event Title
    doc.setFontSize(16)
    doc.setFont("Helvetica", "bold")
    doc.setTextColor(255, 255, 255)
    // Multiline handling for title
    const splitTitle = doc.splitTextToSize(event.title, 118)
    doc.text(splitTitle, 15, 52)

    // Details Grid
    doc.setFontSize(10)
    doc.setFont("Helvetica", "bold")
    doc.setTextColor(33, 150, 243)
    doc.text("DATE", 15, 75)
    doc.text("TIME", 75, 75)
    doc.text("VENUE", 15, 95)

    doc.setFont("Helvetica", "normal")
    doc.setTextColor(200, 200, 200)
    doc.text(event.event_date, 15, 82)
    doc.text(event.event_time, 75, 82)
    doc.text(event.venue, 15, 102)

    // Category
    doc.setFont("Helvetica", "bold")
    doc.setTextColor(33, 150, 243)
    doc.text("CATEGORY", 75, 95)
    doc.setFont("Helvetica", "normal")
    doc.setTextColor(200, 200, 200)
    doc.text(event.categories?.name || "General", 75, 102)

    // Divider line
    doc.setDrawColor(50, 50, 50)
    doc.setLineWidth(0.5)
    doc.line(15, 115, 133, 115)

    // Add QR Code
    if (qrUrl) {
      doc.setFillColor(255, 255, 255)
      doc.rect(49, 125, 50, 50, "F")
      doc.addImage(qrUrl, "PNG", 50, 126, 48, 48)
    }

    // Footer instruction
    doc.setFont("Helvetica", "normal")
    doc.setFontSize(8)
    doc.setTextColor(120, 120, 120)
    doc.text("Present this QR code to organizers at entrance for scanning.", 32, 185)
    doc.text("Generated by Crew Arena campus system.", 46, 192)

    doc.save(`Ticket-${event.title.replace(/\s+/g, "-")}.pdf`)
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-white md:text-3xl">My Tickets & Registrations</h1>
        <p className="text-sm text-zinc-400">View entry codes and download PDF cards for check-in verification.</p>
      </div>

      {tickets.length === 0 ? (
        <div className="rounded-3xl border border-dashed border-zinc-800 p-12 text-center text-zinc-500">
          <p>You have not registered for any events yet.</p>
          <p className="text-xs text-zinc-600 mt-1">Go to Upcoming Events page to join.</p>
        </div>
      ) : (
        <div className="grid gap-6 md:grid-cols-2">
          {tickets.map((t) => {
            const event = t.registration.events
            const qrUrl = qrUrls[t.ticket_code]

            return (
              <div
                key={t.id}
                className="flex flex-col md:flex-row rounded-3xl border border-zinc-800 bg-zinc-900/30 overflow-hidden backdrop-blur-sm"
              >
                {/* Event summary details */}
                <div className="flex-1 p-6 space-y-4">
                  <div className="space-y-1">
                    <span className="inline-flex items-center rounded-full bg-blue-500/10 border border-blue-500/20 px-2 py-0.5 text-[10px] font-bold text-blue-400 uppercase tracking-wider">
                      {event.categories?.name || "Event"}
                    </span>
                    <h3 className="text-lg font-bold text-white leading-tight">{event.title}</h3>
                  </div>

                  <div className="space-y-2 text-xs text-zinc-400">
                    <div className="flex items-center gap-2">
                      <Calendar className="h-4 w-4 text-primary shrink-0" />
                      <span>{event.event_date}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Clock className="h-4 w-4 text-primary shrink-0" />
                      <span>{event.event_time}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <MapPin className="h-4 w-4 text-primary shrink-0" />
                      <span>{event.venue}</span>
                    </div>
                  </div>

                  <div className="pt-2">
                    <button
                      onClick={() => qrUrl && downloadPDF(t, qrUrl)}
                      disabled={!qrUrl}
                      className="inline-flex items-center gap-1.5 rounded-xl bg-zinc-950 border border-zinc-800 px-4 py-2.5 text-xs font-semibold text-white hover:bg-zinc-900 hover:border-zinc-700 transition-all disabled:opacity-50"
                    >
                      <Download className="h-3.5 w-3.5" />
                      Download PDF
                    </button>
                  </div>
                </div>

                {/* QR Display column */}
                <div className="border-t md:border-t-0 md:border-l border-zinc-800 bg-zinc-950/40 p-6 flex flex-col items-center justify-center min-w-[160px]">
                  {qrUrl ? (
                    <div className="space-y-2 text-center">
                      <div className="rounded-2xl bg-white p-2">
                        <img src={qrUrl} alt="QR Code" className="h-28 w-28" />
                      </div>
                      <p className="text-[10px] font-mono text-zinc-500">{t.ticket_code}</p>
                    </div>
                  ) : (
                    <div className="text-zinc-600 text-xs text-center flex flex-col items-center gap-2">
                      <div className="h-10 w-10 border-2 border-dashed border-zinc-700 rounded-full animate-spin border-t-transparent" />
                      <span>Generating QR...</span>
                    </div>
                  )}
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
